apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-jenkins
  namespace: dev
  labels:
    app: jenkins
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          volumeMounts: 
            - mountPath: /var/jenkins_home
              name: my-volume-jenkins
      volumes:
        - name: my-volume-jenkins
          hostPath: 
            path: /home/ec2-user/jenkins
            type: Directory
