apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-jenkins
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-jenkins
  template:
    metadata:
      labels:
        app: my-jenkins
    spec:
      containers:
      - name: my-jenkins-container
        image: jenkins/jenkins:lts
        volumeMounts: 
          - mountPath: /home/ec2-user/jenkins
            name: my-volume-jenkins
      volumes:
        - name: my-volume-jenkins
          hostPath: 
            path: /home/ec2-user/jenkins
            type: Directory            
