apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: jenkins-storage
  resources:
    requests:
      storage: 4Gi
