apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
spec:
  type: NodePort
  selector:
    app: my-grafana
  ports:
    - name: port1
      protocol: TCP
      port: 3001
      targetPort: 3000
      nodePort: 30005
