apiVersion: v1
kind: LimitRange
metadata:
  name: my-limitrange
  namespace: dev
spec:
  limits:
    - default:
        cpu: 1
        memory: 500Mi
      defaultRequest: 
        cpu: 0.5
        memory: 250Mi
      type: Container	  	  


#kubectl get limitrange -n dev
#kubectl describe n dev
