#Create a Secret by providing credentials on the command line
#kubectl create secret docker-registry regcred --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>


#<your-registry-server> is your Private Docker Registry FQDN. Use https://index.docker.io/v1/ for DockerHub.
#<your-name> is your Docker username.
#<your-pword> is your Docker password.
#<your-email> is your Docker email.


apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: harshahd18/newrepo_20_03:21
  imagePullSecrets:
  - name: regcred


